version: '3.9'

services:
  postgres:
    container_name: recipe_postgres
    image: postgres:16.2-alpine
    ports:
      - "54321:5432"
    volumes:
      - ~/databases/postgres/recipe:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cr3t0
      - POSTGRES_USER=recipe
      - POSTGRES_DB=db_recipe