name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build-deploy:
    name: Continuous Integration RecipeAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Check Styles
        run: ./gradlew build checkstyleMain

      - name: Unit Tests
        run: ./gradlew build test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
